services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 7957692959:AAGYNF8vHZaHanfSIxjc-l3rtxBALhJ6PDE
